query GetPersons {
  persons {
    __typename
    id
    name
    age
    ... on Student {
      universityName
    }
    ... on Employee {
      companyName
    }
  }
}

mutation AddStudent {
  addStudent(input: {
    firstName: "John"
    lastName: "Stanley"
    dateOfBirth: "1991-11-30T00:00:00.000Z"
    universityName: "Uni 1"
  }) {
    id
    age
  }
}

mutation AddEmployee {
  addEmployee(input: {
    firstName: "Mary"
    lastName: "Jim"
    dateOfBirth: "1995-07-23T00:00:00.000Z"
    companyName: "Company 1"
  }) {
    id
    age
  }
}
